apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-container
          image: kush/your-nodejs-image:v1
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: "200m"   # Set CPU limit to 200 milliCPU (0.2 CPU cores)
              memory: "256Mi"  # Set memory limit to 256 MiB
            requests:
              cpu: "100m"   # Request 100 milliCPU (0.1 CPU cores)
              memory: "128Mi"  # Request 128 MiB
